/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LawRouteImport } from './routes/law'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLandlordRouteImport } from './routes/_authenticated/landlord'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as VerifyReportIdRouteImport } from './routes/verify.$reportId'
import { Route as AuthenticatedComparePropertyIdRouteImport } from './routes/_authenticated/compare.$propertyId'
import { Route as AuthenticatedDemandPropertyIdRouteImport } from './routes/_authenticated/demand.$propertyId'
import { Route as AuthenticatedLandlordReportIdRouteImport } from './routes/_authenticated/landlord.$reportId'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties.$propertyId'
import { Route as AuthenticatedPropertiesNewRouteImport } from './routes/_authenticated/properties.new'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedScanReportIdRouteImport } from './routes/_authenticated/scan.$reportId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LawRoute = LawRouteImport.update({
  id: '/law',
  path: '/law',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLandlordRoute = AuthenticatedLandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyReportIdRoute = VerifyReportIdRouteImport.update({
  id: '/verify/$reportId',
  path: '/verify/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComparePropertyIdRoute =
  AuthenticatedComparePropertyIdRouteImport.update({
    id: '/compare/$propertyId',
    path: '/compare/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandPropertyIdRoute =
  AuthenticatedDemandPropertyIdRouteImport.update({
    id: '/demand/$propertyId',
    path: '/demand/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandlordReportIdRoute =
  AuthenticatedLandlordReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedLandlordRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesNewRoute =
  AuthenticatedPropertiesNewRouteImport.update({
    id: '/properties/new',
    path: '/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScanReportIdRoute =
  AuthenticatedScanReportIdRouteImport.update({
    id: '/scan/$reportId',
    path: '/scan/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/law': typeof LawRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/landlord': typeof AuthenticatedLandlordRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/verify/$reportId': typeof VerifyReportIdRoute
  '/compare/$propertyId': typeof AuthenticatedComparePropertyIdRoute
  '/demand/$propertyId': typeof AuthenticatedDemandPropertyIdRoute
  '/landlord/$reportId': typeof AuthenticatedLandlordReportIdRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/scan/$reportId': typeof AuthenticatedScanReportIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/law': typeof LawRoute
  '/pricing': typeof PricingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/landlord': typeof AuthenticatedLandlordRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/verify/$reportId': typeof VerifyReportIdRoute
  '/compare/$propertyId': typeof AuthenticatedComparePropertyIdRoute
  '/demand/$propertyId': typeof AuthenticatedDemandPropertyIdRoute
  '/landlord/$reportId': typeof AuthenticatedLandlordReportIdRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/scan/$reportId': typeof AuthenticatedScanReportIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/law': typeof LawRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/landlord': typeof AuthenticatedLandlordRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/verify/$reportId': typeof VerifyReportIdRoute
  '/_authenticated/compare/$propertyId': typeof AuthenticatedComparePropertyIdRoute
  '/_authenticated/demand/$propertyId': typeof AuthenticatedDemandPropertyIdRoute
  '/_authenticated/landlord/$reportId': typeof AuthenticatedLandlordReportIdRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/_authenticated/properties/new': typeof AuthenticatedPropertiesNewRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/scan/$reportId': typeof AuthenticatedScanReportIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/law'
    | '/pricing'
    | '/dashboard'
    | '/landlord'
    | '/auth/callback'
    | '/checkout/return'
    | '/verify/$reportId'
    | '/compare/$propertyId'
    | '/demand/$propertyId'
    | '/landlord/$reportId'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/reports/$reportId'
    | '/scan/$reportId'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/law'
    | '/pricing'
    | '/dashboard'
    | '/landlord'
    | '/auth/callback'
    | '/checkout/return'
    | '/verify/$reportId'
    | '/compare/$propertyId'
    | '/demand/$propertyId'
    | '/landlord/$reportId'
    | '/properties/$propertyId'
    | '/properties/new'
    | '/reports/$reportId'
    | '/scan/$reportId'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/law'
    | '/pricing'
    | '/_authenticated/dashboard'
    | '/_authenticated/landlord'
    | '/auth/callback'
    | '/checkout/return'
    | '/verify/$reportId'
    | '/_authenticated/compare/$propertyId'
    | '/_authenticated/demand/$propertyId'
    | '/_authenticated/landlord/$reportId'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/properties/new'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/scan/$reportId'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LawRoute: typeof LawRoute
  PricingRoute: typeof PricingRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  VerifyReportIdRoute: typeof VerifyReportIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law': {
      id: '/law'
      path: '/law'
      fullPath: '/law'
      preLoaderRoute: typeof LawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landlord': {
      id: '/_authenticated/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof AuthenticatedLandlordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$reportId': {
      id: '/verify/$reportId'
      path: '/verify/$reportId'
      fullPath: '/verify/$reportId'
      preLoaderRoute: typeof VerifyReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compare/$propertyId': {
      id: '/_authenticated/compare/$propertyId'
      path: '/compare/$propertyId'
      fullPath: '/compare/$propertyId'
      preLoaderRoute: typeof AuthenticatedComparePropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demand/$propertyId': {
      id: '/_authenticated/demand/$propertyId'
      path: '/demand/$propertyId'
      fullPath: '/demand/$propertyId'
      preLoaderRoute: typeof AuthenticatedDemandPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landlord/$reportId': {
      id: '/_authenticated/landlord/$reportId'
      path: '/$reportId'
      fullPath: '/landlord/$reportId'
      preLoaderRoute: typeof AuthenticatedLandlordReportIdRouteImport
      parentRoute: typeof AuthenticatedLandlordRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/new': {
      id: '/_authenticated/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthenticatedPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan/$reportId': {
      id: '/_authenticated/scan/$reportId'
      path: '/scan/$reportId'
      fullPath: '/scan/$reportId'
      preLoaderRoute: typeof AuthenticatedScanReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedLandlordRouteChildren {
  AuthenticatedLandlordReportIdRoute: typeof AuthenticatedLandlordReportIdRoute
}

const AuthenticatedLandlordRouteChildren: AuthenticatedLandlordRouteChildren = {
  AuthenticatedLandlordReportIdRoute: AuthenticatedLandlordReportIdRoute,
}

const AuthenticatedLandlordRouteWithChildren =
  AuthenticatedLandlordRoute._addFileChildren(
    AuthenticatedLandlordRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLandlordRoute: typeof AuthenticatedLandlordRouteWithChildren
  AuthenticatedComparePropertyIdRoute: typeof AuthenticatedComparePropertyIdRoute
  AuthenticatedDemandPropertyIdRoute: typeof AuthenticatedDemandPropertyIdRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRoute
  AuthenticatedPropertiesNewRoute: typeof AuthenticatedPropertiesNewRoute
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedScanReportIdRoute: typeof AuthenticatedScanReportIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLandlordRoute: AuthenticatedLandlordRouteWithChildren,
  AuthenticatedComparePropertyIdRoute: AuthenticatedComparePropertyIdRoute,
  AuthenticatedDemandPropertyIdRoute: AuthenticatedDemandPropertyIdRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRoute,
  AuthenticatedPropertiesNewRoute: AuthenticatedPropertiesNewRoute,
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedScanReportIdRoute: AuthenticatedScanReportIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LawRoute: LawRoute,
  PricingRoute: PricingRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  VerifyReportIdRoute: VerifyReportIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
